name: MinePets
version: '${version}'
main: id.rajaopak.minepets.MinePets
api-version: '1.17'
authors: [rajaopak]
description: Show your pet!
website: https://github.com/rajaopak
softdepend: [ LuckPerms ]
